# Generated by Django 2.0.4 on 2018-05-05 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aris', '0003_auto_20180505_1517'),
        ('universityloanoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('signed', 'signed'), ('unsigned', 'unsigned')], max_length=10)),
                ('signature_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aris.Student', unique=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universityloanoffice.Student', unique=True)),
            ],
        ),
    ]
