# Generated by Django 2.0.4 on 2018-06-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universityloanoffice', '0003_auto_20180526_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('discontinued', 'discontinued'), ('continuous', 'continuous'), ('postponed', 'postponed'), ('completed', 'completed')], max_length=12),
        ),
    ]
