# Generated by Django 2.0.4 on 2018-04-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('programe_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('tuition_fee', models.FloatField()),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aris.College')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('form_four_index_no', models.CharField(max_length=18)),
                ('signature', models.BinaryField()),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('discontinue', 'discontinue'), ('continous', 'continous'), ('postpone', 'postpone')], max_length=12)),
                ('year_of_study', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('programe_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aris.Degree')),
            ],
        ),
    ]
