# Generated by Django 2.0.4 on 2018-05-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris', '0002_auto_20180504_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='signature',
            field=models.CharField(max_length=256),
        ),
    ]
