# Generated by Django 2.0.4 on 2018-05-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris', '0003_auto_20180505_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('discontinued', 'discontinued'), ('continuous', 'continuous'), ('postpone', 'postpone')], max_length=12),
        ),
    ]
