# Generated by Django 2.0.4 on 2018-06-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aris', '0005_auto_20180526_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
