# Generated by Django 2.0.4 on 2018-06-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('reg_no', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('form_four_index_no', models.CharField(max_length=18)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('year_of_study', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('programe_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('discontinued', 'discontinued'), ('continuous', 'continuous'), ('postpone', 'postpone'), ('complete', 'complete')], max_length=12)),
                ('account_no', models.CharField(max_length=25)),
                ('bank_name', models.CharField(max_length=10)),
                ('tuition_fee', models.FloatField()),
                ('accomodation', models.FloatField()),
                ('special_faculty', models.FloatField()),
                ('field', models.FloatField()),
                ('project_and_research', models.FloatField()),
            ],
        ),
    ]
