from django.contrib import admin
from django.urls import path
from universityloanoffice import views

urlpatterns = [
    path('profile/', views.profile),
    path('logout/', views.logoutuser),
    path('notifications/', views.notifications),
    path('file/<path:file_name>', views.showfile),
    path('search-student', views.searchstudent),
    path('import-for-signing/<file_name>', views.import_for_signing),
    path('signing-progress/', views.signing_progress),
    path('export-signed/', views.export_signed),
    path('export-unsigned/', views.export_unsigned),
    path('export-all/', views.export_all),
    path('end-signing-session/', views.end_signing_session),
    path('fill-random-data/', views.fill_random_data),
    path('aggregate-info/<status>', views.aggregate_info),
    path('send-updates/', views.send_updates),
    path('fill/', views.filldata),
    path('manage-loanbeneficiaries/', views.manage_loanbeneficiary),
    path('view-changes/', views.view_changes),
    path('loanbeneficiary/update-status/<reg_no>', views.update_status),
    path('randomizestatus/', views.randomize_student_status),
    path('view-complete/', views.view_complete),
    path('loanbeneficiary/delete/<reg_no>', views.delete_students_with_complete_status),
    path('toggle-signing-status/<reg_no>', views.toggle_signing_status),
    path('inital-import-status/', views.view_initial_import),
    path('import-initial-beneficiaries/<file_name>', views.import_initial_beneficiaries),
    path('initial-file/<file_name>', views.show_initial_file),
    path('send-barcode/', views.receive_barcode),
    path('generate-barcode/', views.generate_barcode),
    path('sign/', views.sign),
    path('ajax/', views.ajax),
    path('ajax-get-status/<reg_no>', views.get_signing_status),
    path('ajax-get-signing-progress/', views.get_signing_progress),
    path('email-configuration/', views.email_configuration),
    path('configure-email', views.configure_email),
    path('web-notf-configuration/', views.web_notf_configuration),
    path('configure-web-notf', views.configure_web_notf),
    path('send-email/', views.send_massmail),
]
